WARNING:2023-04-05 10:29:47,014:app:Starting the db connection to display patient's details in the report
INFO:2023-04-05 10:29:47,141:app:Displayed patient's details in the list
INFO:2023-04-05 10:29:47,141:app:Displayed patient's details in the list
WARNING:2023-04-05 10:29:47,143:app:Hence details displayed, closing the connection
WARNING:2023-04-05 10:29:47,143:app:Hence details displayed, closing the connection
WARNING:2023-04-05 10:29:47,143:app:Hence details displayed, closing the connection
WARNING:2023-04-05 10:29:57,246:app:Starting the db connection to search patients in the list
WARNING:2023-04-05 10:29:57,246:app:Starting the db connection to search patients in the list
WARNING:2023-04-05 10:29:57,246:app:Starting the db connection to search patients in the list
WARNING:2023-04-05 10:29:57,246:app:Starting the db connection to search patients in the list
INFO:2023-04-05 10:29:57,450:app:Displayed all patients with Andrew in the list
INFO:2023-04-05 10:29:57,450:app:Displayed all patients with Andrew in the list
INFO:2023-04-05 10:29:57,450:app:Displayed all patients with Andrew in the list
INFO:2023-04-05 10:29:57,450:app:Displayed all patients with Andrew in the list
INFO:2023-04-05 10:29:57,450:app:Displayed all patients with Andrew in the list
WARNING:2023-04-05 10:29:57,451:app:Hence details displayed, closing the connection
WARNING:2023-04-05 10:29:57,451:app:Hence details displayed, closing the connection
WARNING:2023-04-05 10:29:57,451:app:Hence details displayed, closing the connection
WARNING:2023-04-05 10:29:57,451:app:Hence details displayed, closing the connection
WARNING:2023-04-05 10:29:57,451:app:Hence details displayed, closing the connection
WARNING:2023-04-05 10:29:57,451:app:Hence details displayed, closing the connection
WARNING:2023-04-05 12:42:03,328:app:Starting the db connection to display all patients in the list
INFO:2023-04-05 12:42:03,584:app:Displayed list of all patients in the list
INFO:2023-04-05 12:42:03,584:app:Displayed list of all patients in the list
WARNING:2023-04-05 12:42:03,587:app:Closing the connection
WARNING:2023-04-05 12:42:03,587:app:Closing the connection
WARNING:2023-04-05 12:42:03,587:app:Closing the connection
WARNING:2023-04-14 12:53:26,384:app:Starting the db connection to add tests to be done 
INFO:2023-04-14 12:53:26,656:app:{'tests': 'Hemoglobin, Sugar, BP'} tests has been told by the doctor
INFO:2023-04-14 12:53:26,656:app:{'tests': 'Hemoglobin, Sugar, BP'} tests has been told by the doctor
WARNING:2023-04-14 12:53:26,657:settings:Hence account created, closing the connection
ERROR:2023-04-14 12:53:26,657:app:Exception on /patients/tests/1 [PUT]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hospital/settings.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hospital/app.py", line 189, in add_ordered_tests
    return jsonify({"message": f"{data[0]} tests has been told by the doctor",
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hospital/settings.py", line 32, in wrapper
    except psycopg2.Error as error:
NameError: name 'psycopg2' is not defined
ERROR:2023-04-14 12:53:26,657:app:Exception on /patients/tests/1 [PUT]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hospital/settings.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hospital/app.py", line 189, in add_ordered_tests
    return jsonify({"message": f"{data[0]} tests has been told by the doctor",
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hospital/settings.py", line 32, in wrapper
    except psycopg2.Error as error:
NameError: name 'psycopg2' is not defined
WARNING:2023-04-14 12:53:58,033:app:Starting the db connection to add tests to be done 
INFO:2023-04-14 12:53:58,770:app:{'tests': 'Hemoglobin, Sugar, BP'} tests has been told by the doctor
INFO:2023-04-14 12:53:58,770:app:{'tests': 'Hemoglobin, Sugar, BP'} tests has been told by the doctor
WARNING:2023-04-14 12:53:58,770:settings:Hence account created, closing the connection
WARNING:2023-04-14 12:55:32,681:app:Starting the db connection to add tests to be done 
WARNING:2023-04-14 12:55:33,337:settings:Hence account created, closing the connection
ERROR:2023-04-14 12:55:33,337:app:Exception on /patients/tests/1 [PUT]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hospital/settings.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hospital/app.py", line 188, in add_ordered_tests
    logger(__name__).info(f"{data['results']} tests has been told by the doctor")
KeyError: 'results'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hospital/settings.py", line 32, in wrapper
    except psycopg2.Error as error:
NameError: name 'psycopg2' is not defined
ERROR:2023-04-14 12:55:33,337:app:Exception on /patients/tests/1 [PUT]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hospital/settings.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hospital/app.py", line 188, in add_ordered_tests
    logger(__name__).info(f"{data['results']} tests has been told by the doctor")
KeyError: 'results'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hospital/settings.py", line 32, in wrapper
    except psycopg2.Error as error:
NameError: name 'psycopg2' is not defined
WARNING:2023-04-14 12:56:29,942:app:Starting the db connection to add tests to be done 
INFO:2023-04-14 12:56:30,205:app:<built-in method items of dict object at 0x7ff581d1b6c0> tests has been told by the doctor
INFO:2023-04-14 12:56:30,205:app:<built-in method items of dict object at 0x7ff581d1b6c0> tests has been told by the doctor
WARNING:2023-04-14 12:56:30,205:settings:Hence account created, closing the connection
WARNING:2023-04-14 12:56:53,452:app:Starting the db connection to add tests to be done 
WARNING:2023-04-14 12:56:53,713:settings:Hence account created, closing the connection
ERROR:2023-04-14 12:56:53,713:app:Exception on /patients/tests/1 [PUT]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hospital/settings.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hospital/app.py", line 188, in add_ordered_tests
    logger(__name__).info(f"{data.results} tests has been told by the doctor")
AttributeError: 'dict' object has no attribute 'results'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hospital/settings.py", line 32, in wrapper
    except psycopg2.Error as error:
NameError: name 'psycopg2' is not defined
ERROR:2023-04-14 12:56:53,713:app:Exception on /patients/tests/1 [PUT]
Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/Hospital/settings.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hospital/app.py", line 188, in add_ordered_tests
    logger(__name__).info(f"{data.results} tests has been told by the doctor")
AttributeError: 'dict' object has no attribute 'results'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bc2113451/Desktop/VS Code/Oops/.venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/bc2113451/Desktop/VS Code/Oops/Hospital/settings.py", line 32, in wrapper
    except psycopg2.Error as error:
NameError: name 'psycopg2' is not defined
WARNING:2023-04-14 12:57:48,064:app:Starting the db connection to add tests to be done 
INFO:2023-04-14 12:57:48,328:app:dict_values(['Hemoglobin, Sugar, BP']) tests has been told by the doctor
INFO:2023-04-14 12:57:48,328:app:dict_values(['Hemoglobin, Sugar, BP']) tests has been told by the doctor
WARNING:2023-04-14 12:57:48,329:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:01:13,436:app:Starting the db connection to add tests to be done 
INFO:2023-04-14 13:01:13,792:app:Hemoglobin, Sugar, BP tests has been told by the doctor
INFO:2023-04-14 13:01:13,792:app:Hemoglobin, Sugar, BP tests has been told by the doctor
WARNING:2023-04-14 13:01:13,792:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:05:49,168:app:Starting the db connection to add tests to be done 
INFO:2023-04-14 13:05:49,367:app:Abc, Xyz tests has been told by the doctor
INFO:2023-04-14 13:05:49,367:app:Abc, Xyz tests has been told by the doctor
WARNING:2023-04-14 13:05:49,367:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:06:25,265:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:06:25,265:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:06:25,265:app:Starting the db connection to add tests results
INFO:2023-04-14 13:06:26,592:app:Results of test: {'tests': 'Negative in all'} 
INFO:2023-04-14 13:06:26,592:app:Results of test: {'tests': 'Negative in all'} 
INFO:2023-04-14 13:06:26,592:app:Results of test: {'tests': 'Negative in all'} 
INFO:2023-04-14 13:06:26,592:app:Results of test: {'tests': 'Negative in all'} 
WARNING:2023-04-14 13:06:26,593:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:06:26,593:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:06:50,332:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:06:50,332:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:06:50,332:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:06:50,332:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:06:50,332:app:Starting the db connection to add tests results
INFO:2023-04-14 13:06:50,548:app:Results of test: {'tests': 'Positive in Abc'} 
INFO:2023-04-14 13:06:50,548:app:Results of test: {'tests': 'Positive in Abc'} 
INFO:2023-04-14 13:06:50,548:app:Results of test: {'tests': 'Positive in Abc'} 
INFO:2023-04-14 13:06:50,548:app:Results of test: {'tests': 'Positive in Abc'} 
INFO:2023-04-14 13:06:50,548:app:Results of test: {'tests': 'Positive in Abc'} 
INFO:2023-04-14 13:06:50,548:app:Results of test: {'tests': 'Positive in Abc'} 
WARNING:2023-04-14 13:06:50,549:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:06:50,549:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:06:50,549:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:09:05,647:app:Starting the db connection to add prescription
INFO:2023-04-14 13:09:05,867:app:Lemonade, Eye drops, Vicks has been given by the doctor
INFO:2023-04-14 13:09:05,867:app:Lemonade, Eye drops, Vicks has been given by the doctor
WARNING:2023-04-14 13:09:05,868:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:09:21,440:app:Starting the db connection to add prescription
WARNING:2023-04-14 13:09:21,440:app:Starting the db connection to add prescription
WARNING:2023-04-14 13:09:21,440:app:Starting the db connection to add prescription
INFO:2023-04-14 13:09:21,765:app:Ear drops, hair oil has been given by the doctor
INFO:2023-04-14 13:09:21,765:app:Ear drops, hair oil has been given by the doctor
INFO:2023-04-14 13:09:21,765:app:Ear drops, hair oil has been given by the doctor
INFO:2023-04-14 13:09:21,765:app:Ear drops, hair oil has been given by the doctor
WARNING:2023-04-14 13:09:21,766:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:09:21,766:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:09:52,848:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:09:52,848:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:09:52,848:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:09:52,848:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:09:52,848:app:Starting the db connection to add tests results
INFO:2023-04-14 13:09:53,078:app:Results of test: {'results': 'Positive in Abc'} 
INFO:2023-04-14 13:09:53,078:app:Results of test: {'results': 'Positive in Abc'} 
INFO:2023-04-14 13:09:53,078:app:Results of test: {'results': 'Positive in Abc'} 
INFO:2023-04-14 13:09:53,078:app:Results of test: {'results': 'Positive in Abc'} 
INFO:2023-04-14 13:09:53,078:app:Results of test: {'results': 'Positive in Abc'} 
INFO:2023-04-14 13:09:53,078:app:Results of test: {'results': 'Positive in Abc'} 
WARNING:2023-04-14 13:09:53,079:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:09:53,079:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:09:53,079:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:10:02,374:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:10:02,374:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:10:02,374:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:10:02,374:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:10:02,374:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:10:02,374:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:10:02,374:app:Starting the db connection to add tests results
INFO:2023-04-14 13:10:02,983:app:Results of test: {'results': 'Positive in Abc'} 
INFO:2023-04-14 13:10:02,983:app:Results of test: {'results': 'Positive in Abc'} 
INFO:2023-04-14 13:10:02,983:app:Results of test: {'results': 'Positive in Abc'} 
INFO:2023-04-14 13:10:02,983:app:Results of test: {'results': 'Positive in Abc'} 
INFO:2023-04-14 13:10:02,983:app:Results of test: {'results': 'Positive in Abc'} 
INFO:2023-04-14 13:10:02,983:app:Results of test: {'results': 'Positive in Abc'} 
INFO:2023-04-14 13:10:02,983:app:Results of test: {'results': 'Positive in Abc'} 
INFO:2023-04-14 13:10:02,983:app:Results of test: {'results': 'Positive in Abc'} 
WARNING:2023-04-14 13:10:02,984:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:10:02,984:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:10:02,984:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:10:02,984:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:10:19,553:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:10:19,553:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:10:19,553:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:10:19,553:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:10:19,553:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:10:19,553:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:10:19,553:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:10:19,553:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:10:19,553:app:Starting the db connection to add tests results
INFO:2023-04-14 13:10:19,835:app:Results of test: {'results': 'Negative in all'} 
INFO:2023-04-14 13:10:19,835:app:Results of test: {'results': 'Negative in all'} 
INFO:2023-04-14 13:10:19,835:app:Results of test: {'results': 'Negative in all'} 
INFO:2023-04-14 13:10:19,835:app:Results of test: {'results': 'Negative in all'} 
INFO:2023-04-14 13:10:19,835:app:Results of test: {'results': 'Negative in all'} 
INFO:2023-04-14 13:10:19,835:app:Results of test: {'results': 'Negative in all'} 
INFO:2023-04-14 13:10:19,835:app:Results of test: {'results': 'Negative in all'} 
INFO:2023-04-14 13:10:19,835:app:Results of test: {'results': 'Negative in all'} 
INFO:2023-04-14 13:10:19,835:app:Results of test: {'results': 'Negative in all'} 
INFO:2023-04-14 13:10:19,835:app:Results of test: {'results': 'Negative in all'} 
WARNING:2023-04-14 13:10:19,835:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:10:19,835:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:10:19,835:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:10:19,835:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:10:19,835:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:10:57,184:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:10:57,184:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:10:57,184:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:10:57,184:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:10:57,184:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:10:57,184:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:10:57,184:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:10:57,184:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:10:57,184:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:10:57,184:app:Starting the db connection to add tests results
WARNING:2023-04-14 13:10:57,184:app:Starting the db connection to add tests results
INFO:2023-04-14 13:10:58,004:app:Results of test: {'results': 'Positive in Abc'} 
INFO:2023-04-14 13:10:58,004:app:Results of test: {'results': 'Positive in Abc'} 
INFO:2023-04-14 13:10:58,004:app:Results of test: {'results': 'Positive in Abc'} 
INFO:2023-04-14 13:10:58,004:app:Results of test: {'results': 'Positive in Abc'} 
INFO:2023-04-14 13:10:58,004:app:Results of test: {'results': 'Positive in Abc'} 
INFO:2023-04-14 13:10:58,004:app:Results of test: {'results': 'Positive in Abc'} 
INFO:2023-04-14 13:10:58,004:app:Results of test: {'results': 'Positive in Abc'} 
INFO:2023-04-14 13:10:58,004:app:Results of test: {'results': 'Positive in Abc'} 
INFO:2023-04-14 13:10:58,004:app:Results of test: {'results': 'Positive in Abc'} 
INFO:2023-04-14 13:10:58,004:app:Results of test: {'results': 'Positive in Abc'} 
INFO:2023-04-14 13:10:58,004:app:Results of test: {'results': 'Positive in Abc'} 
INFO:2023-04-14 13:10:58,004:app:Results of test: {'results': 'Positive in Abc'} 
WARNING:2023-04-14 13:10:58,005:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:10:58,005:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:10:58,005:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:10:58,005:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:10:58,005:settings:Hence account created, closing the connection
WARNING:2023-04-14 13:10:58,005:settings:Hence account created, closing the connection
WARNING:2023-04-14 16:01:46,501:app:Starting the db connection to update payment status
INFO:2023-04-14 16:01:46,853:app:Payment status of patient id 1 has been updated to Done
INFO:2023-04-14 16:01:46,853:app:Payment status of patient id 1 has been updated to Done
WARNING:2023-04-14 16:01:46,854:settings:Hence account created, closing the connection
WARNING:2023-04-14 16:02:01,511:app:Starting the db connection to update payment status
WARNING:2023-04-14 16:02:01,511:app:Starting the db connection to update payment status
WARNING:2023-04-14 16:02:01,511:app:Starting the db connection to update payment status
INFO:2023-04-14 16:02:02,010:app:Payment status of patient id 2 has been updated to pending
INFO:2023-04-14 16:02:02,010:app:Payment status of patient id 2 has been updated to pending
INFO:2023-04-14 16:02:02,010:app:Payment status of patient id 2 has been updated to pending
INFO:2023-04-14 16:02:02,010:app:Payment status of patient id 2 has been updated to pending
WARNING:2023-04-14 16:02:02,011:settings:Hence account created, closing the connection
WARNING:2023-04-14 16:02:02,011:settings:Hence account created, closing the connection
